<?php

/**
 * @file
 * Includes the autoloader created by Composer.
 *
 * This file was generated by drupal-scaffold.
 *
 * @see composer.json
 * @see index.php
 * @see core/install.php
 * @see core/rebuild.php
 * @see core/modules/statistics/statistics.php
 */

/*return require_once(realpath('vendor/autoload.php'));*/
return require_once(realpath('C:/xampp/htdocs/project/maldegem1/vendor/autoload.php'));

/*
require __DIR__ . '/../vendor/autoload.php';
*/